# Generated by Django 5.0.2 on 2024-03-18 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_livro_capa"),
    ]

    operations = [
        migrations.AddField(
            model_name="autor",
            name="email",
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
