# Generated by Django 4.2.14 on 2024-07-29 14:26

import core.models.user
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_user_foto"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Usuário", "verbose_name_plural": "Usuários"},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", core.models.user.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AddField(
            model_name="user",
            name="passage_id",
            field=models.CharField(default="default_passa_id_value", max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
