# Generated by Django 4.2.14 on 2024-09-13 18:09

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_itenscompra_preco_alter_user_passage_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="compra",
            name="data",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="passage_id",
            field=models.CharField(
                default=uuid.UUID("179069d1-0fb2-4124-88d2-d1874d5615fb"), max_length=255, unique=True
            ),
        ),
    ]
